version: 0.2

env:
  variables:
    ACCOUNT_ID: "713881797197"
    REGION: "us-east-1"
    REPO_NAME: "ecommerce-ecr"
    IMAGE_TAG: "latest"

phases:
  install:
    runtime-versions:
      java: corretto11
      docker: 20
    commands:
      - echo Installing required tools...
      - yum install -y jq curl unzip
      - echo Installing kubectl...
      - curl -o kubectl https://s3.us-east-1.amazonaws.com/amazon-eks/1.27.0/2023-11-14/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/
      - echo Configuring kubeconfig for EKS cluster...
      - aws eks update-kubeconfig --region $REGION --name eks-cluster-three-tier-1

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com

  build:
    commands:
      - echo Building the JAR file with Maven...
      - mvn clean install
      - echo Building the Docker image...
      - docker build -t ${REPO_NAME}:${IMAGE_TAG} .
      - docker tag ${REPO_NAME}:${IMAGE_TAG} ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${REPO_NAME}:${IMAGE_TAG}

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${REPO_NAME}:${IMAGE_TAG}
      - echo Deploying to EKS...
      - sed "s|IMAGE_PLACEHOLDER|${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${REPO_NAME}:${IMAGE_TAG}|g" k8s/deployment.yaml | kubectl apply -f -
      - kubectl apply -f k8s/service.yaml
      - kubectl apply -f k8s/mongodb-deployment.yaml
      - kubectl apply -f k8s/mongodb-service.yaml

artifacts:
  base-directory: k8s
  files:
    - deployment.yaml
    - service.yaml
    - mongodb-deployment.yaml
    - mongodb-service.yaml
