AWSTemplateFormatVersion: '2010-09-09'
Description: EKS Control Plane

Parameters:
  VpcId:
    Type: String
  SubnetIds:
    Type: List<String>

Resources:
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: ecommerce-cluster
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds: !Ref SubnetIds

Outputs:
  ClusterName:
    Value: !Ref EKSCluster
  ClusterRoleArn:
    Value: !GetAtt EKSClusterRole.Arn
